name: Go tests

on: 
  push:
  pull_request:
  merge

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - run: go test -v -coverfile= coverage.out ./learning/1_fundamentals ./learning/2_Data_Modeling
      - run: go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt
      - name: Check Coverage threshold
        run: |
          COVERAGE= $(cat coverage.txt)
          echo "Test Coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then 
            echo "X Test coverage is ${COVERAGE}%, which is below  the reqiured 50% threshold"
            exit 1
          else
            echo "Test coverage is ${COVERAGE}% which meets the 50% threshold"
          fi  