name: Go tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test -v -coverprofile=coverage.out \
            ./learning/1_fundamentals/... \
            ./learning/2_Data_Modeling/...

      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | awk '/total:/ {gsub("%", "", $3); print $3}')

          echo "Test Coverage: ${COVERAGE}%"

          awk -v coverage="$COVERAGE" 'BEGIN {
            if (coverage < 50) {
              printf "X Test coverage is %.2f%%, which is below the required 50%% threshold\n", coverage
              exit 1
            } else {
              printf "Test coverage is %.2f%%, which meets the 50%% threshold\n", coverage
            }
          }'